http:
  middlewares:
    head-to-get:
      plugin:
        head_to_get:
          putOriginalMethodInHeader: "X-Original-Request-Method"
  routers:
    test:
      rule: "PathPrefix(`/`)"
      middlewares:
        - head-to-get
      service: api@internal
